[project]
name = "rclpy-async"
version = "0.10"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vassily Lyutsarev", email = "vassilyl@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.10.0",
]

[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
